<template>
	<div
		class="component_home_frame">
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
		<div>内容</div>
	</div>
</template>

<script src="./Home.js"></script>

<style scoped lang="less" src="./Home.less"></style>